spring:
  datasource:
    password: Root@123
    url: jdbc:mysql://localhost:3306/microservices?serverTimezone=UTC
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
