spring:
  datasource:
    password: passtodev
    url: jdbc:mysql://localhost:3306/microservices-dev?serverTimezone=UTC
    username: dev
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
